name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Merge master into current branch
      run: |
        cd /root/server/loggn
        git pull origin/master

    - name: Set up SSH agent
      run: |
        eval $(ssh-agent -s)
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
        ssh-keyscan -H 60.204.240.235 >> ~/.ssh/known_hosts

    - name: Deploy
      run: |
        ssh -v root@60.204.240.235 'cd /root/server/loggn && hugo --baseURL http://60.204.240.235'

