name: CI

on:
  push:
    branches:
      - master  # 监视主分支的推送

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy
      run: |
        ssh-keyscan -H 60.204.240.235 >> ~/.ssh/known_hosts
        # ssh -T root@60.204.240.235 << 'EOF'
        ssh -T root@60.204.240.235 'cd /root/server/loggn && hugo --baseURL http://60.204.240.235'
