name: CI

on:
  push:
    branches:
      - master  # 监视主分支的推送

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 在 GitHub Secrets 中存储 SSH 密钥
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key root@60.204.240.235 'cd /root/server/loggn && hugo --baseURL http://60.204.240.235'
